[tools]
"aqua:rvben/rumdl" = "latest"
"aqua:tombi-toml/tombi" = "latest"
"github:zizmorcore/zizmor" = "latest"
"npm:@actions/languageserver" = "latest"
"npm:oxfmt" = "latest"
rust = { version = "nightly", components = "rust-analyzer" }
